---
- name: Build Nautobot Ansible collection spec
  ansible.builtin.set_fact:
    nautobot_ansible_collection_spec: >-
      {{ nautobot_ansible_collection_name }}{{
        ':' ~ nautobot_ansible_collection_version
        if nautobot_ansible_collection_version | length > 0
        else ''
      }}

- name: Build Nautobot Ansible collection install command
  ansible.builtin.set_fact:
    nautobot_ansible_galaxy_command:
      - ansible-galaxy
      - collection
      - install
      - "{{ nautobot_ansible_collection_spec }}"

- name: Add Nautobot Ansible collection upgrade option
  ansible.builtin.set_fact:
    nautobot_ansible_galaxy_command: "{{ nautobot_ansible_galaxy_command + ['--upgrade'] }}"
  when: nautobot_ansible_collection_upgrade | bool

- name: Add Nautobot Ansible collection force option
  ansible.builtin.set_fact:
    nautobot_ansible_galaxy_command: "{{ nautobot_ansible_galaxy_command + ['--force'] }}"
  when: nautobot_ansible_collection_force | bool

- name: Install Nautobot Ansible collection
  ansible.builtin.command:
    argv: "{{ nautobot_ansible_galaxy_command }}"
  register: nautobot_ansible_collection_install
  changed_when: >-
    'Nothing to do' not in nautobot_ansible_collection_install.stdout
    and 'Skipping' not in nautobot_ansible_collection_install.stdout

- name: Install Nautobot Ansible Python dependencies
  ansible.builtin.command:
    argv: >-
      {{
        [nautobot_ansible_python, '-m', 'pip', 'install']
        + (
          nautobot_ansible_pip_extra_args.split()
          if nautobot_ansible_pip_extra_args | length > 0
          else []
        )
        + nautobot_ansible_python_packages
      }}
  register: nautobot_ansible_pip_install
  changed_when: >-
    'Requirement already satisfied' not in nautobot_ansible_pip_install.stdout
