---
nautobot_url: >-
  {{
    lookup('ansible.builtin.env', 'NAUTOBOT_URL')
    | default(vault_nautobot_url | default(''), true)
  }}
nautobot_token: >-
  {{
    lookup('ansible.builtin.env', 'NAUTOBOT_TOKEN')
    | default(vault_nautobot_token | default(''), true)
  }}
nautobot_validate_certs: true
