---
- name: Prepare Prometheus runtime variables
  ansible.builtin.import_tasks: prereqs.yml

- name: Install Prometheus binaries and assets
  ansible.builtin.import_tasks: install.yml

- name: Configure Prometheus service
  ansible.builtin.import_tasks: config.yml
