connection_path: local
ansible_host: >-
  {{
    tailscale_ip
    if connection_path == 'tailscale' and tailscale_ip is defined
    else local_ip | default(inventory_hostname)
  }}
default_user: "{{ vault_default_user }}"
ansible_become_password: "{{ vault_ansible_become_password }}"
nautobot_url: >-
  {{
    lookup('ansible.builtin.env', 'NAUTOBOT_URL')
    | default(vault_nautobot_url | default(''), true)
  }}
nautobot_token: >-
  {{
    lookup('ansible.builtin.env', 'NAUTOBOT_TOKEN')
    | default(vault_nautobot_token | default(''), true)
  }}
nautobot_validate_certs: true
